name: gridwalk

volumes:
  postgres_data:
  geodatabase_data:

services:
  postgres:
    image: postgres:16
    container_name: gridwalk-postgres
    platform: linux/amd64
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gridwalk
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"

  geodatabase:
    image: postgis/postgis:16-3.4
    container_name: gridwalk-geodatabase
    platform: linux/amd64
    volumes:
      - geodatabase_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gridwalk
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5437:5432"
