name: gridwalk

services:
  geodatabase:
    image: postgis/postgis:16-3.4
    container_name: gridwalk-geodatabase
    platform: linux/amd64
    volumes:
      - ./local/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gridwalk
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  postgres:
    image: postgres:16
    container_name: gridwalk-postgres
    platform: linux/amd64
    volumes:
      - ./local/postgresql-backend/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gridwalk
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: gridwalk-dynamodb
    ports:
      - "8000:8000"
    volumes:
      - ./local/dynamodb:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"

  dynamodb-local-init:
    image: amazon/aws-cli:2.22.33
    environment:
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      AWS_DEFAULT_REGION: us-east-1
    entrypoint: /usr/bin/env bash
    command: >
      -c '
      aws dynamodb create-table \
        --table-name gridwalk \
        --attribute-definitions \
          AttributeName=PK,AttributeType=S \
          AttributeName=SK,AttributeType=S \
          AttributeName=user_id,AttributeType=S \
          AttributeName=con_id,AttributeType=S \
        --key-schema \
          AttributeName=PK,KeyType=HASH \
          AttributeName=SK,KeyType=RANGE \
        --global-secondary-indexes \
          "[ \
          {\"IndexName\":\"user\",\"KeySchema\":[{\"AttributeName\":\"user_id\",\"KeyType\":\"HASH\"}],\"Projection\":{\"ProjectionType\":\"ALL\"}}, \
          {\"IndexName\":\"con\",\"KeySchema\":[{\"AttributeName\":\"con_id\",\"KeyType\":\"HASH\"}],\"Projection\":{\"ProjectionType\":\"ALL\"}} \
          ]" \
        --billing-mode PAY_PER_REQUEST \
        --endpoint-url http://dynamodb:8000'
