name: gridwalk

services:
  geodatabase:
    image: postgis/postgis:16-3.4
    container_name: gridwalk-geodatabase
    platform: linux/amd64
    volumes:
      - ./local/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gridwalk
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  postgres:
    image: postgres:16
    container_name: gridwalk-postgres
    platform: linux/amd64
    volumes:
      - ./local/postgresql-backend/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gridwalk
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
